[package]
name = "nimiq-client"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Nimiq's Rust client"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]
exclude = ["db", "peer_key.dat"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
futures = "0.1"
log = "0.4"
tokio = "0.1"
nimiq-blockchain-base = { path = "../blockchain-base", version = "0.1"}
nimiq-consensus = { path = "../consensus", version = "0.1" }
nimiq-metrics-server = {path = "../metrics-server", version = "0.1" }
nimiq-primitives = { path = "../primitives", version = "0.1" }
nimiq-rpc-server = { path = "../rpc-server", version = "0.1" }

[dependencies.nimiq-lib]
path = "../lib"
version = "0.1"
features = [
    "validator",
    "rpc-server",
    "metrics-server",
    "ws-rpc-server",
    "deadlock",
    "logging",
    "panic"
]
