[package]
name = "nimiq-handel"
version = "0.1.0"
authors = ["Janosch Gräf <janosch@nimiq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1"
futures = "0.1"
futures-cpupool = "0.1"
lazy_static = "1.3"
log = "0.4"
parking_lot = "0.9"
rand = "0.7"
tokio = "0.1"

beserial = { path = "../beserial", version = "0.1" }
beserial_derive = { path = "../beserial/beserial_derive", version = "0.1" }
nimiq-bls = { path = "../bls", version = "0.1" }
nimiq-collections = { path = "../collections", version = "0.1", features = ["bitset"] }
nimiq-hash = { path = "../hash", version = "0.1" }
nimiq-macros = { path = "../macros", version = "0.1" }
nimiq-utils = { path = "../utils", version = "0.1", features = ["math", "mutable-once", "observer", "timers"] }
nimiq-handel-primitives = { path = "./primitives", version = "0.1" }
